feat: add sonarqube conventions
tailrocks/tailrocks-gradle-conventions pull request #44
Opened 2022-10-07 10:08 UTC by yahorbarkouski

2022-10-07 12:14 UTC, donbeave requested changes

2022-10-07 12:14 UTC, donbeave commented on sonarqube-conventions/src/main/kotlin/com/tailrocks/gradle/SonarqubePlugin.kt
> +            property("sonar.host.url", System.getenv("SONAR_HOST"))
Let's rename to SONAR_HOST_URL

2022-10-07 12:14 UTC, donbeave commented on sonarqube-conventions/src/main/kotlin/com/tailrocks/gradle/SonarqubePlugin.kt
> +            property("sonar.login", System.getenv("SONAR_TOKEN"))
Rename to SONAR_LOGIN

2022-10-07 12:14 UTC, donbeave commented on sonarqube-conventions/src/main/kotlin/com/tailrocks/gradle/SonarqubePlugin.kt
> +            property("sonar.projectVersion", System.getenv("GIT_COMMIT_SHORTHASH") ?: "")
Rename to SONAR_PROJECT_VERSION

2022-10-07 12:14 UTC, donbeave commented on sonarqube-conventions/src/main/kotlin/com/tailrocks/gradle/SonarqubePlugin.kt
> +                property("sonar.pullrequest.provider", System.getProperty("sonar.pullrequest.provider", "github"))
Is it default value `github`?

2022-10-07 12:14 UTC, donbeave commented on sonarqube-conventions/src/main/kotlin/com/tailrocks/gradle/SonarqubePlugin.kt
> +                property("sonar.branch.name", System.getenv("CI_COMMIT_REF_NAME") ?: "master")
Let's not autofill with master, if env is empty, just put null or don't add this property.

2022-10-17 20:23 UTC, yahorbarkouski commented on sonarqube-conventions/src/main/kotlin/com/tailrocks/gradle/SonarqubePlugin.kt
> +                property("sonar.pullrequest.provider", System.getProperty("sonar.pullrequest.provider", "github"))
yeah

2022-10-17 21:24 UTC, donbeave requested changes

2022-10-17 22:21 UTC, donbeave approved these changes

2022-10-17 22:21 UTC, merged